#!/bin/sh
# Ash isn't supported properly in spellcheck static analyzer
# Using debian based version (kind of similar)
# shellcheck shell=dash
[ -f /etc/config/justclash ] || exit 0

add_missing_option() {
    local path="$1"
    local default_value="$2"

    if ! uci -q get "$path" >/dev/null; then
        uci set "$path"="$default_value"
    fi
}

clean_fake_ip_list() {
    local option="$1"
    local list_val item new_val
    local need_clean=0

    list_val=$(uci -q get "justclash.proxy.$option")
    [ -n "$list_val" ] || return 0

    for item in $list_val; do
        case "$item" in
            +.*) need_clean=1; break ;;
        esac
    done

    [ "$need_clean" = "1" ] || return 0

    uci -q delete "justclash.proxy.$option"
    for item in $list_val; do
        new_val="${item#+.}"
        uci add_list "justclash.proxy.$option=$new_val"
    done
}

add_missing_option "justclash.settings.routing_mode" "full"
add_missing_option "justclash.settings.mihomo_core_source_type" "github"
add_missing_option "justclash.settings.mihomo_github_repo" "MetaCubeX/mihomo"
add_missing_option "justclash.settings.mihomo_github_channel" "alpha"
add_missing_option "justclash.settings.mihomo_custom_core_url" ""
add_missing_option "justclash.settings.mihomo_rulesets_files_download_url" "https://cdn.jsdelivr.net/gh/saltymonkey/mrs-parsed-data"
add_missing_option "justclash.settings.mihomo_dashboard_zashboard_url" "https://github.com/Zephyruso/zashboard/releases/latest/download/dist-no-fonts.zip"
add_missing_option "justclash.settings.mihomo_dashboard_metacubexd_url" "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"
add_missing_option "justclash.settings.mihomo_dashboard_yacd_meta_url" "https://github.com/MetaCubeX/Yacd-meta/archive/refs/heads/gh-pages.zip"
add_missing_option "justclash.settings.wait_for_wan" "0"
add_missing_option "justclash.settings.wait_for_wan_max" "90"
add_missing_option "justclash.settings.mihomo_mem_limit" "0"
add_missing_option "justclash.settings.nft_doh_mode" "BY RULES"
add_missing_option "justclash.settings.mihomo_service_data_autoupdate" "0"
add_missing_option "justclash.settings.mihomo_cron_service_data_update_string" "0 4 * * 0"
add_missing_option "justclash.settings.mihomo_scheduled_work" "0"
add_missing_option "justclash.settings.mihomo_cron_scheduled_work_start_string" "0 5 * * *"
add_missing_option "justclash.settings.mihomo_cron_scheduled_work_stop_string" "0 23 * * *"
add_missing_option "justclash.proxy.sniffer_override_destination" "0"
add_missing_option "justclash.proxy.api_tls" "0"
add_missing_option "justclash.proxy.api_tls_cert" "/etc/uhttpd.crt"
add_missing_option "justclash.proxy.api_tls_key" "/etc/uhttpd.key"
add_missing_option "justclash.settings.mihomo_geosite_url" "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
add_missing_option "justclash.settings.mihomo_geoip_url" "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
add_missing_option "justclash.settings.ipv6_enabled" "0"
add_missing_option "justclash.proxy.fake_ip_range6" "fdfe:dcba:9876::1/64"
add_missing_option "justclash.proxy.geodata_mode" "0"
add_missing_option "justclash.proxy.geodata_autoupdate" "0"
add_missing_option "justclash.proxy.geodata_autoupdate_interval" "24"

if ! uci -q get justclash.settings.nft_ports_exclude >/dev/null; then
    uci add_list justclash.settings.nft_ports_exclude='6881'
fi

uci -q delete justclash.settings.mihomo_autoupdate
uci -q delete justclash.settings.mihomo_autoupdate_channel
uci -q delete justclash.settings.mihomo_cron_update_string

if [ "$(uci -q get justclash.proxy.fake_ip_ttl)" = "1" ]; then
    uci set justclash.proxy.fake_ip_ttl="60"
fi

if ! uci -q get justclash.proxy.sniffer_exclude_domain | grep -qF "*"; then
    uci add_list justclash.proxy.sniffer_exclude_domain='*'
fi

clean_fake_ip_list "fake_ip_exclude_domains"

# Remove deprecated fake_ip options from routing sections
for section in $(uci -q show justclash | sed -n 's/^justclash\.\(.*\)=proxies$/\1/p'); do
    uci -q delete "justclash.$section.fake_ip"
done
for section in $(uci -q show justclash | sed -n 's/^justclash\.\(.*\)=proxy_group$/\1/p'); do
    uci -q delete "justclash.$section.fake_ip"
done
uci -q delete justclash.direct_rules

for section in $(uci -q show justclash | sed -n 's/^justclash\.\(.*\)=proxy_provider$/\1/p'); do
    uci -q rename "justclash.$section.subscription_useragent_support=header_user_agent"
    uci -q rename "justclash.$section.subscription_authorization_support=header_authorization"
    uci -q rename "justclash.$section.subscription_hwid_support=header_hwid"
    uci -q rename "justclash.$section.age_public_key=header_age_public_key"
done

uci commit justclash

exit 0
