 services:
  stable-builder:
    image: saltymonkey/owrt-sdk-stable-cached:latest
    container_name: stable-builder
    volumes:
      - ./justclash:/builder/package/feeds/utilites/justclash
      - ./luci-app-justclash:/builder/package/feeds/luci/luci-app-justclash
      - ./output/stable:/output
    working_dir: /builder
    command: >
      /bin/sh -c "
      make defconfig &&
      make package/justclash/compile V=s -j2 &&
      make package/luci-app-justclash/compile V=s -j2 &&
      cp bin/packages/x86_64/utilites/justclash_*.ipk /output/ &&
      cp bin/packages/x86_64/luci/luci-app-justclash_*.ipk /output/
      "

  snapshot-builder:
    image: openwrt/sdk:x86-64-snapshot
    container_name: snapshot-builder
    volumes:
      - ./justclash:/builder/package/feeds/utilites/justclash
      - ./luci-app-justclash:/builder/package/feeds/luci/luci-app-justclash
      - ./output/snapshot:/output
    working_dir: /builder
    command: >
      /bin/sh -c "
      make defconfig &&
      make package/justclash/compile V=s -j2 &&
      make package/luci-app-justclash/compile V=s -j2 &&
      cp bin/packages/x86_64/utilites/justclash_*.apk /output/ &&
      cp bin/packages/x86_64/luci/luci-app-justclash_*.apk /output/
      "