 services:
  ipk-builder:
    image: saltymonkey/owrt-sdk-ipk-cached:latest
    container_name: ipk-builder
    volumes:
        - ./justclash:/builder/package/feeds/utilites/justclash
        - ./luci-app-justclash:/builder/package/feeds/luci/luci-app-justclash
        - ./output/ipk:/output
    working_dir: /builder
    command: >
        /bin/bash -c "
        rm -f bin/packages/x86_64/luci/luci-i18n-justclash-ru_*.ipk &&
        make defconfig && \
        make package/justclash/compile V=s -j2 && \
        make package/luci-app-justclash/compile V=s -j2 && \
        for f in bin/packages/x86_64/utilites/justclash_*.ipk bin/packages/x86_64/luci/luci-app-justclash_*.ipk bin/packages/x86_64/luci/luci-i18n-justclash-ru_*.ipk; do \
            [ -e \"$$f\" ] || continue; \
            base=$$(basename \"$$f\"); \
            newname=\"$${base/_/-}\"; \
            cp \"$$f\" \"/output/$$newname\"; \
        done
        "

  apk-builder:
    image: saltymonkey/owrt-sdk-apk-cached:latest
    container_name: apk-builder
    volumes:
        - ./justclash:/builder/package/feeds/utilites/justclash
        - ./luci-app-justclash:/builder/package/feeds/luci/luci-app-justclash
        - ./output/apk:/output
    working_dir: /builder
    command: >
        /bin/bash -c "
        rm -f bin/packages/x86_64/luci/luci-i18n-justclash-ru-*.apk &&
        make defconfig &&
        make package/justclash/compile V=s -j2 &&
        make package/luci-app-justclash/compile V=s -j2 &&
        cp bin/packages/x86_64/utilites/justclash-*.apk /output/ &&
        cp bin/packages/x86_64/luci/luci-app-justclash-*.apk /output/ &&
        cp bin/packages/x86_64/luci/luci-i18n-justclash-ru-*.apk /output/
        "