FROM openwrt/sdk:x86-64-25.12.4

WORKDIR /builder
ENV APK_APKGEN=1

RUN ./scripts/feeds update -a && \
    ./scripts/feeds install luci-base nftables coreutils jq curl inotify-tools && \
    mkdir -p package/feeds/utilities/ package/feeds/luci/

COPY --chown=buildbot:buildbot ./justclash package/feeds/utilities/justclash
COPY --chown=buildbot:buildbot ./luci-app-justclash package/feeds/luci/luci-app-justclash

RUN sed -i 's/^[[:space:]]*DEPENDS:=.*/\tEXTRA_DEPENDS:=nftables (>=0), coreutils-base64 (>=0), jq-full (>=0), curl (>=0), kmod-nft-tproxy (>=0), kmod-nf-tproxy (>=0), ca-bundle (>=0), zoneinfo-all (>=0), inotifywait (>=0), libinotifytools (>=0)\n\tDEPENDS:=/' package/feeds/utilities/justclash/Makefile && \
    sed -i 's/^[[:space:]]*LUCI_DEPENDS:=.*/\tEXTRA_DEPENDS:=luci-base (>=0), justclash (>=0)\nLUCI_DEPENDS:=/' package/feeds/luci/luci-app-justclash/Makefile && \
    make defconfig && \
    make package/justclash/compile package/luci-app-justclash/compile -j1
