#!/bin/sh /etc/rc.common

# directive for procd from openwrt -> unused in code
# shellcheck disable=SC2034
USE_PROCD=1
START=99
STOP=01
PIDFILE="/var/run/justclash.pid"
FIFOPATH="/tmp/justclash/justclash.fifo"
PROG="/usr/bin/justclash"

start_service() {
    procd_open_instance
    procd_set_param command $PROG start
    procd_set_param env JUSTCLASH_ENV=procd
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn 60 0 3
    procd_set_param pidfile $PIDFILE
    procd_close_instance
}

stop_service() {
    $PROG stop
    rm -f "$PIDFILE" 2>/dev/null
    rm -f "$FIFOPATH" 2>/dev/null
}

reload_service() {
    $PROG reload
    return $?
}

restart() {
    $PROG reload
}
