#!/bin/sh /etc/rc.common
# shellcheck shell=dash
# directive for procd from openwrt -> unused in code
# shellcheck disable=SC2034
USE_PROCD=1
START=99
STOP=01
PROGNAME="justclash"
PROG="/usr/bin/${PROGNAME}"
RELOAD_DELAY_MS=1000

start_service() {
    procd_open_instance
    procd_set_param command "$PROG" start
    procd_set_param env JUSTCLASH_ENV=procd
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param norespawn
    procd_close_instance
}

stop_service() {
    $PROG stop 2>&1
    sleep 1
}

reload_service() {
    $PROG reload 2>&1
    return $?
}

restart() {
    $PROG reload 2>&1
}

service_triggers() {
    local autorestart_at_interface_change autorestart_controlled_interfaces
    config_load "$PROGNAME"
    config_get_bool autorestart_at_interface_change settings autorestart_at_interface_change 0
    config_get autorestart_controlled_interfaces settings autorestart_controlled_interfaces

    # Thx ITDog
    # TODO: Check if this variable have effect on all procd instance
    PROCD_RELOAD_DELAY=$RELOAD_DELAY_MS
    if [ "$autorestart_at_interface_change" -eq 1 ]; then
            for iface in $autorestart_controlled_interfaces; do
                procd_add_interface_trigger "interface.*.up" "$iface" /etc/init.d/"${PROGNAME}" reload
            done
    fi
}
