#!/bin/sh /etc/rc.common
# shellcheck shell=dash
# directive for procd from openwrt -> unused in code
# shellcheck disable=SC2034
USE_PROCD=1
START=99
STOP=1
PROGNAME="justclash"
PROG="/usr/bin/${PROGNAME}"
DELAY_TIMEOUT=2000

# shellcheck disable=SC1091
[ -r /lib/functions.sh ] && . /lib/functions.sh
# shellcheck disable=SC1091
[ -r /lib/config/uci.sh ] && . /lib/config/uci.sh

start_service() {
    procd_open_instance
    procd_set_param command "$PROG" start
    procd_set_param env JUSTCLASH_ENV=procd
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param norespawn
    procd_close_instance
}

stop_service() {
    $PROG stop
    sleep 1
}

reload_service() {
    stop
    start
}

restart() {
    stop
    start
}

boot() {
    local delayed_boot delayed_boot_value

    config_load "$PROGNAME"
    config_get_bool delayed_boot settings delayed_boot 0
    config_get delayed_boot_value settings delayed_boot_value 8

    if [ "$delayed_boot" -eq 1 ]; then
        logger -p "user.info" -t "$PROGNAME" "Delayed start was enabled. Delaying..."
        sleep "$delayed_boot_value"
    fi

    start
}

service_triggers()
{
    PROCD_RELOAD_DELAY=$DELAY_TIMEOUT
    procd_add_reload_trigger "$PROGNAME"
}
