FROM openwrt/sdk:x86_64-v24.10.5
WORKDIR /builder
RUN ./scripts/feeds update -a \
    && ./scripts/feeds install luci-base \
    && mkdir -p /builder/package/feeds/utilities/ \
    && mkdir -p /builder/package/feeds/luci/