#!/bin/ash
# shellcheck shell=dash
# shellcheck disable=SC2034

# Process-wide immutable application contract shared by the CLI and sourced modules.

PROGNAME="justclash"
JUSTCLASH_VERSION="__COMPILED_VERSION_VARIABLE__"
NO_DATA_STRING="N/A"

CORE_BIN_NAME="mihomo"
CORE_PATH="/usr/bin/${CORE_BIN_NAME}"
CORE_WORKDIR_PATH="/tmp/${PROGNAME}"
CORE_WORKDIR_RULES_PATH="${CORE_WORKDIR_PATH}/rules"
CORE_WORKDIR_CACHE_DB_PATH="${CORE_WORKDIR_PATH}/cache.db"
CORE_WORKDIR_UCI_HASH_PATH="${CORE_WORKDIR_PATH}/uci.hash"
OUTPUT_YAML_CONFIG_PATH="${CORE_WORKDIR_PATH}/config.yaml"
ACTIVE_IPCIDR_RULESETS_PATH="${CORE_WORKDIR_PATH}/active_ipcidr_rulesets.cache"
ACTIVE_STATIC_IPS_PATH="${CORE_WORKDIR_PATH}/active_static_ips.cache"
ASYNC_WORKER_PID_PATH="/var/run/${PROGNAME}_async_worker.pid"

INITD_PATH="/etc/init.d/${PROGNAME}"
PROG_PATH="/usr/bin/${PROGNAME}.sh"

PROG_ETC_DIR="/etc/${PROGNAME}"
RULESETS_BLOCKS_FILENAME="block.rulesets.txt"
RULESETS_FILENAME="rulesets.txt"
USER_RULESETS_FILENAME="user.rulesets.txt"
USER_RULESETS_BLOCKS_FILENAME="user.block.rulesets.txt"
SYMLINKDIR_RULESETS="${PROG_ETC_DIR}/rules"
SYMLINK_CACHE_DB_PATH="${PROG_ETC_DIR}/cache.db"
RULESETS_BLOCKS_FILE="${PROG_ETC_DIR}/${RULESETS_BLOCKS_FILENAME}"
RULESETS_FILE="${PROG_ETC_DIR}/${RULESETS_FILENAME}"
USER_RULESETS_FILE="${PROG_ETC_DIR}/${USER_RULESETS_FILENAME}"
USER_RULESETS_BLOCKS_FILE="${PROG_ETC_DIR}/${USER_RULESETS_BLOCKS_FILENAME}"

DASHBOARD_PATH="${PROG_ETC_DIR}/dashboard"

ETC_CONFIG_DIR="/etc/config"
DEFAULT_CONFIG_PATH="${PROG_ETC_DIR}/default.config"
CONFIG_PATH="${ETC_CONFIG_DIR}/${PROGNAME}"
CONFIG_BAK_PATH="${ETC_CONFIG_DIR}/${PROGNAME}.bak"

NSLOOKUP_TIMEOUT=5
WARN_PATTERNS_DHCP_CONFIG="podkop_server podkop_noresolv podkop_cachesize doh_backup_noresolv doh_backup_server doh_server"
DHCP_CONFIG_FILEPATH="/etc/config/dhcp"
RESOLVCONF_FILEPATH="/etc/resolv.conf"
ZAPRETINITD_FILEPATH="/etc/init.d/zapret"
BYEDPI_FILEPATH="/etc/init.d/byedpi"
YOUTUBEUNBLOCK_FILEPATH="/etc/init.d/youtubeUnblock"
B4_FILEPATH="/etc/init.d/b4"
REQUIRED_TOOLS="jq nft curl md5sum ntpd base64 inotifywait"

NF_TABLE_NAME="${PROGNAME}_tproxy"
NF_TABLE_FWMARK_FINAL=3
NF_TABLE_FWMARK_PROXY=255
NF_ROUTE_TABLE=100

JUSTCLASH_CONSTANTS_LOADED=1

readonly \
    PROGNAME \
    JUSTCLASH_VERSION \
    NO_DATA_STRING \
    CORE_BIN_NAME \
    CORE_PATH \
    CORE_WORKDIR_PATH \
    CORE_WORKDIR_RULES_PATH \
    CORE_WORKDIR_CACHE_DB_PATH \
    CORE_WORKDIR_UCI_HASH_PATH \
    OUTPUT_YAML_CONFIG_PATH \
    ACTIVE_IPCIDR_RULESETS_PATH \
    ACTIVE_STATIC_IPS_PATH \
    ASYNC_WORKER_PID_PATH \
    INITD_PATH \
    PROG_PATH \
    PROG_ETC_DIR \
    RULESETS_BLOCKS_FILENAME \
    RULESETS_FILENAME \
    USER_RULESETS_FILENAME \
    USER_RULESETS_BLOCKS_FILENAME \
    SYMLINKDIR_RULESETS \
    SYMLINK_CACHE_DB_PATH \
    RULESETS_BLOCKS_FILE \
    RULESETS_FILE \
    USER_RULESETS_FILE \
    USER_RULESETS_BLOCKS_FILE \
    DASHBOARD_PATH \
    ETC_CONFIG_DIR \
    DEFAULT_CONFIG_PATH \
    CONFIG_PATH \
    CONFIG_BAK_PATH \
    NSLOOKUP_TIMEOUT \
    WARN_PATTERNS_DHCP_CONFIG \
    DHCP_CONFIG_FILEPATH \
    RESOLVCONF_FILEPATH \
    ZAPRETINITD_FILEPATH \
    BYEDPI_FILEPATH \
    YOUTUBEUNBLOCK_FILEPATH \
    B4_FILEPATH \
    REQUIRED_TOOLS \
    NF_TABLE_NAME \
    NF_TABLE_FWMARK_FINAL \
    NF_TABLE_FWMARK_PROXY \
    NF_ROUTE_TABLE \
    JUSTCLASH_CONSTANTS_LOADED
