#!/bin/ash
# shellcheck shell=dash

help() {
    echo "Usage: justclash.sh <command> [args]"
    echo ""
    echo "Service Management:"
    echo "  start|run               Start the service"
    echo "  stop                    Stop the service"
    echo "  version package         Show JustClash package version"
    echo "  version core            Show Mihomo core version"
    echo ""
    echo "Resources:"
    echo "  resources core update                  Update Mihomo if a newer version is available"
    echo "  resources core remove [-y|-Y|--yes]    Remove the installed Mihomo binary"
    echo "  resources data update                  Update built-in service data"
    echo ""
    echo "Schedule:"
    echo "  schedule sync                          Synchronize scheduled jobs from UCI"
    echo ""
    echo "Diagnostics:"
    echo "  check                              Run a safe, redacted diagnostic summary"
    echo "  check full --unsafe                Run the full local diagnostic report"
    echo "  check nft                          Inspect nftables state"
    echo "  check routes                       Inspect policy-routing state"
    echo "  check ping TARGET [COUNT]          Test ICMP connectivity"
    echo "  check dns-proxy DOMAIN             Test Mihomo DNS resolution"
    echo "  check dns-external DOMAIN RESOLVER Test an explicitly selected resolver"
    echo "  check hwid                         Show Hardware ID (HWID)"
    echo ""
    echo "Configuration:"
    echo "  config show mihomo [--unsafe]            Show generated Mihomo configuration"
    echo "  config show service [--unsafe]           Show service configuration"
    echo "  config reset [-y|-Y|--yes]               Reset service configuration to default"
    echo ""
    echo "Logs:"
    echo "  logs service [N]        Show last N JustClash entries from the system log (default 40)"
    echo "  logs system [N]         Show the same entries (compatibility alias)"
    echo ""
    echo "Help:"
    echo "  help|?|command          Show this help message"
    echo ""
}
