#!/bin/ash
# shellcheck shell=dash

help() {
    echo "Usage: justclash.sh <command> [args]"
    echo ""
    echo "Service Management:"
    echo "  start|run               Start the service"
    echo "  stop                    Stop the service"
    echo "  info_core|version_core  Show Mihomo core version"
    echo "  info_package|version    Show service version"
    echo "  service_data_update     Update service files from repository"
    echo ""
    echo "Mihomo management Commands:"
    echo "  core_update                     Check current version and update Mihomo if a newer version is available"
    echo "  core_remove                     Remove the currently installed Mihomo binary"
    echo ""
    echo "  cron_update                     Update all scheduled tasks from UCI settings"
    echo ""
    echo "Diagnostics:"
    echo "  show_hwid                   Show Hardware ID (HWID)"
    echo "  diag_report                 Run diagnostic"
    echo "  diag_nft                    Run nftables diagnostic"
    echo "  diag_route                  Run route tables diagnostic"
    echo "  diag_icmp                   Run internet check with ICMP"
    echo "  diag_proxy_resolver         Run Internal DNS diagnostic"
    echo "  diag_external_resolver      Run Default DNS diagnostic"
    echo "  diag_mihomo_config          Show generated mihomo config (redacted)"
    echo "  diag_mihomo_config_unsafe   Show raw generated mihomo config (includes passwords)"
    echo "  diag_service_config         Show service config (redacted)"
    echo "  diag_service_config_unsafe  Show raw service config (includes passwords)"
    echo "  config_reset                Reset service configuration to default"
    echo ""
    echo "Logs:"
    echo "  logs|systemlogs [N]     Show last N lines of system logs (default 40)"
    echo ""
    echo "Help:"
    echo "  help|?|command          Show this help message"
    echo ""
}
