name: Build packages
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    name: Build justclash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Check version match
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          JUSTCLASH_VERSION=$(grep '^PKG_VERSION:=' justclash/Makefile | cut -d '=' -f 2)
          LUCI_APP_JUSTCLASH_VERSION=$(grep '^PKG_VERSION:=' luci-app-justclash/Makefile | cut -d '=' -f 2)

          echo "Justclash: $JUSTCLASH_VERSION"
          echo "Luci-app-justclash: $LUCI_APP_JUSTCLASH_VERSION"
          echo "Pushed tag: $TAG_VERSION"

          if [ "$JUSTCLASH_VERSION" != "$TAG_VERSION" ] || [ "$LUCI_APP_JUSTCLASH_VERSION" != "$TAG_VERSION" ]; then
            echo "Error: Version mismatch. Release build cancelled."
            exit 1
          fi

      - name: Build and push stable
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile-stable
          context: .
          tags: justclash/build:stable

      - name: Create Stable Docker container
        run: docker create --name stable justclash/build:stable

      - name: Copy files from stable Docker container
        run: |
          mkdir -p ./output
          rm -f ./output/*.ipk
          docker cp stable:/builder/bin/packages/x86_64/utilites/. ./output/
          docker cp stable:/builder/bin/packages/x86_64/luci/. ./output/
          rm -rf ./output/tmp

      - name: Rename all output packages (replace first _ with -)
        shell: bash
        run: |
          for f in ./output/*.ipk; do
            [ -e "$f" ] || continue
            base=$(basename "$f")
            newname=$(echo "$base" | sed 's/_/-/')
            mv "$f" "./output/$newname"
          done

      - name: Renaming translation file
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          mv ./output/luci-i18n-justclash-ru-*.ipk "./output/luci-i18n-justclash-ru-${VERSION}.ipk"

      - name: Remove Docker stable container
        run: docker rm stable

      - name: Build and push snapshot
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile-snapshot
          context: .
          tags: justclash/build:snapshot

      - name: Create Snapshot Docker container
        run: docker create --name snapshot justclash/build:snapshot

      - name: Copy files from Snapshot Docker container
        run: |
          mkdir -p ./output
          rm -f ./output/*.apk
          docker cp snapshot:/builder/bin/packages/x86_64/utilites/. ./output/
          docker cp snapshot:/builder/bin/packages/x86_64/luci/. ./output/
          rm -rf ./output/tmp

      - name: Remove Docker snapshot container
        run: docker rm snapshot

      - name: Extract changelog for current version
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          awk '/## \['"$VERSION"'\]/ {flag=1} /^## \[/ {if(flag && !/## \['"$VERSION"'\]/) exit} flag' ./RELEASENOTES.md > ./tmp.md

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./output/*.ipk
            ./output/*.apk
          body_path: ./tmp.md
